
package proxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://WS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param id
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://WS/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://WS/", className = "proxy.GetCompteResponse")
    @Action(input = "http://WS/BanqueService/getCompteRequest", output = "http://WS/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listComptes", targetNamespace = "http://WS/", className = "proxy.ListComptes")
    @ResponseWrapper(localName = "listComptesResponse", targetNamespace = "http://WS/", className = "proxy.ListComptesResponse")
    @Action(input = "http://WS/BanqueService/listComptesRequest", output = "http://WS/BanqueService/listComptesResponse")
    public List<Compte> listComptes();

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionToDh")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionToDh", targetNamespace = "http://WS/", className = "proxy.ConversionToDh")
    @ResponseWrapper(localName = "ConversionToDhResponse", targetNamespace = "http://WS/", className = "proxy.ConversionToDhResponse")
    @Action(input = "http://WS/BanqueService/ConversionToDhRequest", output = "http://WS/BanqueService/ConversionToDhResponse")
    public double conversionToDh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

}
